
import Home from "./components/langing/Home";
import About from "./components/langing/About";
import Work from "./components/langing/Work";
import Testimonial from "./components/langing/Testimonial";
import Contact from "./components/langing/Contact";
import Footer from "./components/langing/Footer";
import Head from 'next/head'

function Application() {
  return (
    <div className="App">
      <Head>
        <title>ALLO GROUP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
      <About />
      <Work />
      <Testimonial />
      <Contact />
      <Footer />
    </div>
  );
}

export default Application;
